server:
  port: 80

app:
  secret-key: $2y$10$B5mCdvQssdCOeK7Xt7r4/ex4rMDshdRaPSGqH.LW8DPgqm4bzAB8K
  file:
    storage:
      path: ${user.home}/teacher-stor/

spring:
  data:
    mongodb:
      database: teacher
      host: localhost
      port: 27017
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - com.kulygin.changelog

management:
  endpoints:
    web:
      base-path: /api/management
      exposure:
        include: [ 'configprops', 'env', 'health', 'info', 'jhimetrics', 'logfile', 'loggers', 'threaddump' ]
  endpoint:
    health:
      show-details: always
    jhimetrics:
      enabled: true
    logfile:
      enabled: true
  metrics:
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true

logging:
  file:
    name: ${user.home}/teacher-stor/library.log